### ISSUE TITLE
Find a new maintainer

### ISSUE THREAD

**Issue by VPashkov** [fsprojects/awesome-fsharp#110]
I'm no longer able to continue to maintain this project and looking for somebody to replace me.
I can suggest @neftedollar as a replacement.
He is willing and capable to do it.
@fsprojects can someone to add @Neftedollar as a maintainer of this repository?

**Comment by Neftedollar** [comment]
I'm here

**Comment by baronfel** [comment]
@forki are you able to do this?

**Comment by forki** [comment]
done

**Comment by baronfel** [comment]
Thanks! As always you're the best :)
