### ISSUE TITLE
Adding OctoLinker to the list

### ISSUE THREAD

**Issue by xt0rted** [fsprojects/awesome-fsharp#125]
Before creating a PR I wanted to see if it was appropriate to add the [OctoLinker](https://octolinker.now.sh/) browser extension to this list?

I've been adding a bunch of .net support to it recently and it currently supports `*.fsproj`, `*.props` & `*.targets` files for linked files & package references along with some other msbuild/nuget related files. Tomorrow's release (October 7th) will add support for Paket files, and a pending PR adds support for .net scripting (scriptcs, Cake, and Fake).

**Comment by Neftedollar** [comment]
@xt0rted first of all thank you for your contribution to OctoLinker! I use this extension every day.

Currently, I don't know is this correct tot add OctoLinker to this list or not.

@vilinski @vasily-kirichenko @forki @gsomix @sergey-tihon @szer

**Comment by Neftedollar** [comment]
// cc @FoggyFinder @VPashkov @Liminiens @atsapura @aensidhe @ForNeVeR

**Comment by FoggyFinder** [comment]
I think it's fine to add OctoLinker

**Comment by vilinski** [comment]
under "Developer Tools/Browser plugins"? But I'm afrait it will stay here alone

**Comment by xt0rted** [comment]
Sounds good. I'll send a PR when FAKE support lands.
