### ISSUE TITLE
Move to fsharp or fsprojects

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/awesome-fsharp#34]
What about moving this repository to fsharp or fsprojects organizations? It'd make it much more visible.

**Comment by VPashkov** [comment]
I would be glad if this happens. 
But I'm not sure know how to initiate this process.

**Comment by vasily-kirichenko** [comment]
@VPashkov I asked @dsyme and he gave you rights to transfer projects to fsprojects organization. Try to do it.

**Comment by VPashkov** [comment]
@vasily-kirichenko, thank you!
But I'm for now I'm getting an error "You don’t have the permission to create repositories on fsprojects" when trying to transfer this project to fsprojects organization.
Maybe I'm doing something wrong or I should wait some time before permission changes will work?

**Comment by dsyme** [comment]
@VPashkov If you make me admin on your project I'll transfer it?

**Comment by VPashkov** [comment]
@dsyme, I made a request to transfer this repository to you.

**Comment by dsyme** [comment]
@VPashkov OK, it's in it's new home https://github.com/fsprojects/awesome-fsharp

**Comment by VPashkov** [comment]
@dsyme, great! Thanks!

**Comment by smoothdeveloper** [comment]
Do we also need to do something with "awesome awesome"?

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper https://github.com/sindresorhus/awesome/pull/939
