### ISSUE TITLE
Add GitHub topics to this repository

### ISSUE THREAD

**Issue by VPashkov** [fsprojects/awesome-fsharp#74]
[List of awesome lists](https://github.com/sindresorhus/awesome) requires that repository has _awesome_ and _awesome-list_ as [GitHub topics](https://help.github.com/articles/about-topics/).
I think we could also add _fsharp_ as a topic.

**Comment by VPashkov** [comment]
@dsyme, I don't have rights to manage topics of this repository.
Could you please add this topics?

**Comment by 7sharp9** [comment]
@dsyme Could you give admin rights to @VPashkov so he can add the tags mentioned?
Not sure who else might have access @forki Do yo happen to know?

**Comment by ForNeVeR** [comment]
I am so sorry we were unable to address this timely. But better late than never, right?

Finally, the tag list has been updated (thank you so much for your work on the repo and noticing this problem), and I will drive the  further inclusion into the root awesome-list (I see [already two failed attempts](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+fsharp+is%3Aclosed), so… we will get there).
