### ISSUE TITLE
Listed as Python project

### ISSUE THREAD

**Issue by algunion** [fsprojects/awesome-fsharp#90]
![pyfsharp](https://user-images.githubusercontent.com/3482227/58278199-288dc900-7da4-11e9-93a6-79766fbdaa7d.png)

Is the .py file really necessary?

**Comment by VPashkov** [comment]
It's not necessary but, it was very helpful at the beginning.
Now this file is a little bit outdated and there is idea rewrite this script in F#.
I made an issue #91 for this. And removed the metadata.py file.
