### ISSUE TITLE
Implement a metadata update script in F#

### ISSUE THREAD

**Issue by VPashkov** [fsprojects/awesome-fsharp#91]
There was a [metadata.py](https://github.com/fsprojects/awesome-fsharp/blob/6d2841a40ffa62e8d31efdacde8668164416052f/metadata.py) file with a script for updated repositories metadata(# of stars, forks etc.).
The idea is to rewrite it to F#.

**Comment by eugene-g** [comment]
Do we really need that metadata? Looks kinda noisy.

**Comment by Neftedollar** [comment]
@eugene-g  good point

**Comment by ForNeVeR** [comment]
I have added _some other_ automation in F# (to manipulate ToC) and dropped the mentioned metadata.

Indeed most of the other awesome-lists don't have anything similar, and it has been mentioned in other places (including [our request on inclusion into the root awesome repo](https://github.com/sindresorhus/awesome/pull/1648)) as distracting and hard to keep up-to-date.
